### ISSUE TITLE
A better Documentation on how to implement this Factory

### ISSUE THREAD

**Issue by MHaendel** [wiseape/payum-sofortuberweisung#2]
Could you please add a simple readme on how to enable and configure this bundle?

**Comment by Gemineye** [comment]
A little readme would be nice :) And is it really necessary to stick to the 0.12 version of payum? It seems that 0.14 is the latest stable version.

**Comment by softint2** [comment]
Its by now 0.15 and I would like to see a little documentation as well.

**Comment by kryptychon** [comment]
There is a official package. Please check it out. See readme. Thank you!
