### ISSUE TITLE
There is an official sofort extension.

### ISSUE THREAD

**Issue by makasim** [wiseape/payum-sofortuberweisung#3]
There is an official extension. I am going to support it and keep in sync with changes in the core. 

https://github.com/Payum/Payum/tree/master/src/Payum/Sofort
https://github.com/Payum/Sofort
https://packagist.org/packages/payum/sofort

Could it be possible to add some words to readme that this package is outdated and mark it as abandoned  on the packagist?

**Comment by kryptychon** [comment]
Hi makasim,

thanks for letting me know. I just added a readme with the info.
Keep up the great work!

**Comment by kryptychon** [comment]
@makasim,

done.

**Comment by makasim** [comment]
Thank you very much
